version: '3'
services:
  app:
    container_name: app
    build:
      context: ./app
    ports:
    - 9229:9229
    - 9000:8080
    volumes:
    - ./app/src/./app/src/
    depends_on:
      - 'backend'
    networks:
      - mynet

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8080
    networks:
      - mynet

networks:
  mynet:
    driver: bridge